---
- name: "openvpn | Check availability cert on CA (S3)"
  amazon.aws.s3_object:
    aws_access_key: "{{
      vars['openvpn_ca_storage_source']['aws_access_key'] | default(omit) }}"
    aws_secret_key: "{{
      vars['openvpn_ca_storage_source']['aws_secret_key'] | default(omit) }}"
    bucket: "{{ vars['openvpn_ca_storage_source']['bucket'] | default(omit) }}"
    expiration: "{{
      vars['openvpn_ca_storage_source']['expiration'] | default(omit) }}"
    ignore_nonexistent_bucket: "true"
    rgw: "{{ vars['openvpn_ca_storage_source']['rgw'] | default(omit) }}"
    endpoint_url: "{{ vars['openvpn_ca_storage_source']['endpoint_url'] |
      default(omit) }}"
    validate_certs: "{{
      vars['openvpn_ca_storage_source']['validate_certs'] | default(omit) }}"
    region: "{{ vars['openvpn_ca_storage_source']['region'] | default(omit) }}"
    profile: "{{
      vars['openvpn_ca_storage_source']['profile'] | default(omit) }}"
    mode: "geturl"
    object: "{{ vars['openvpn_ca_storage_source']['object_prefix'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '.crt' }}"
  register: "openvpn_master_result"
  # Ignore because aws_s3 have not any "check object exists in bucket" mode
  ignore_errors: true
  become: false
  delegate_to: "localhost"
- name: "openvpn | Import fetch root cert from S3 tasks"
  ansible.builtin.import_tasks:
    file: "ca.d/s3/openvpn_s3_get_root.yml"
  become: false
  delegate_to: "localhost"
- name: "openvpn | Import generate certs S3 tasks"
  ansible.builtin.import_tasks:
    file: "ca.d/s3/openvpn_s3_generate_certs.yml"
  when:
    - "vars['openvpn_master_result']['failed']"
  become: false
  delegate_to: "localhost"
- name: "openvpn | Import upload certs to S3 tasks"
  ansible.builtin.import_tasks:
    file: "ca.d/s3/openvpn_s3_put_ca.yml"
  when:
    - "vars['openvpn_master_result']['failed']"
  become: false
  delegate_to: "localhost"
- name: "openvpn | Import fetch certs from S3 tasks"
  ansible.builtin.import_tasks:
    file: "ca.d/s3/openvpn_s3_fetch_certs.yml"
  become: false
  delegate_to: "localhost"
- name: "openvpn | Import fetch OpenVPN files from S3"
  ansible.builtin.import_tasks:
    file: "ca.d/s3/openvpn_s3_fetch_openvpn_files.yml"
  become: false
  delegate_to: "localhost"
