---
- name: "openvpn | Import pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "user.d/prereq.yml"
- name: "openvpn | Import pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "prereq.d/main.yml"
- name: "openvpn | Import find user tasks"
  ansible.builtin.import_tasks:
    file: "user.d/find_user.yml"
- name: "openvpn | Import packages tasks"
  ansible.builtin.import_tasks:
    file: "packages.d/main.yml"
- name: "openvpn | Import CA tasks"
  ansible.builtin.import_tasks:
    file: "ca.d/main.yml"
- name: "openvpn | Import user tasks"
  ansible.builtin.import_tasks:
    file: "user.d/main.yml"
