---
- name: "openvpn | Revoke target cert"
  ansible.builtin.command:
    cmd: "{{ 'openssl ca -config /tmp/openssl.conf -keyfile ' ~
      vars['openvpn_local_fetch_dir'] ~ '/' ~ vars['openvpn_instance_name'] ~
      '/' ~ vars['openvpn_ca_storage_source']['root_key'] ~ ' -cert ' ~
      vars['openvpn_local_fetch_dir'] ~ '/' ~ vars['openvpn_instance_name'] ~
      '/' ~ vars['openvpn_ca_storage_source']['root_crt'] ~ ' -revoke ' ~
      vars['openvpn_local_fetch_dir'] ~ '/' ~ vars['openvpn_instance_name'] ~
      '/' ~ vars['openvpn_instance_name'] ~ '.crt' }}"
  register: "openvpn_revoke_target_cert_result"
  changed_when: "openvpn_revoke_target_cert_result['rc'] == 0"
  failed_when: "openvpn_revoke_target_cert_result['rc'] != 0"
- name: "openvpn | Generate CRL"
  ansible.builtin.command:
    cmd: "{{ 'openssl ca -config /tmp/openssl.conf -keyfile ' ~
      vars['openvpn_local_fetch_dir'] ~ '/' ~ vars['openvpn_instance_name'] ~
      '/' ~ vars['openvpn_ca_storage_source']['root_key'] ~ ' -cert ' ~
      vars['openvpn_local_fetch_dir'] ~ '/' ~ vars['openvpn_instance_name'] ~
      '/' ~ vars['openvpn_ca_storage_source']['root_crt'] ~ ' -gencrl -out ' ~
      vars['openvpn_local_fetch_dir'] ~ '/' ~ vars['openvpn_instance_name'] ~
      '/' ~ 'crl.pem' }}"
  register: "openvpn_generate_crl_result"
  changed_when: "openvpn_generate_crl_result['rc'] == 0"
  failed_when: "openvpn_generate_crl_result['rc'] != 0"
