---
- name: "openvpn | Put crl index to CA (S3)"
  amazon.aws.s3_object:
    aws_access_key: "{{ vars['openvpn_ca_storage_source']['aws_access_key'] |
      default(omit) }}"
    aws_secret_key: "{{ vars['openvpn_ca_storage_source']['aws_secret_key'] |
      default(omit) }}"
    bucket: "{{ vars['openvpn_ca_storage_source']['bucket'] | default(omit) }}"
    encrypt: "{{ vars['openvpn_ca_storage_source']['encrypt'] |
      default(omit) }}"
    ignore_nonexistent_bucket: "true"
    rgw: "{{ vars['openvpn_ca_storage_source']['rgw'] | default(omit) }}"
    endpoint_url: "{{ vars['openvpn_ca_storage_source']['endpoint_url'] |
      default(omit) }}"
    validate_certs: "{{ vars['openvpn_ca_storage_source']['validate_certs'] |
      default(omit) }}"
    region: "{{ vars['openvpn_ca_storage_source']['region'] | default(omit) }}"
    profile: "{{ vars['openvpn_ca_storage_source']['profile'] |
      default(omit) }}"
    mode: "put"
    object: "{{ vars['openvpn_ca_storage_source']['object_prefix'] ~ '/' ~
      vars['openvpn_ca_storage_source']['crl_path'] + '/index' }}"
    overwrite: "different"
    src: "{{ vars['openvpn_local_fetch_dir'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '/index' }}"
- name: "openvpn | Put crl number to CA (S3)"
  amazon.aws.s3_object:
    aws_access_key: "{{ vars['openvpn_ca_storage_source']['aws_access_key'] |
      default(omit) }}"
    aws_secret_key: "{{ vars['openvpn_ca_storage_source']['aws_secret_key'] |
      default(omit) }}"
    bucket: "{{ vars['openvpn_ca_storage_source']['bucket'] | default(omit) }}"
    encrypt: "{{ vars['openvpn_ca_storage_source']['encrypt'] |
      default(omit) }}"
    ignore_nonexistent_bucket: "true"
    rgw: "{{ vars['openvpn_ca_storage_source']['rgw'] | default(omit) }}"
    endpoint_url: "{{ vars['openvpn_ca_storage_source']['endpoint_url'] |
      default(omit) }}"
    validate_certs: "{{ vars['openvpn_ca_storage_source']['validate_certs'] |
      default(omit) }}"
    region: "{{ vars['openvpn_ca_storage_source']['region'] | default(omit) }}"
    profile: "{{ vars['openvpn_ca_storage_source']['profile'] |
      default(omit) }}"
    mode: "put"
    object: "{{ vars['openvpn_ca_storage_source']['object_prefix'] ~ '/' ~
      vars['openvpn_ca_storage_source']['crl_path'] + '/crlnumber' }}"
    overwrite: "different"
    src: "{{ vars['openvpn_local_fetch_dir'] + '/' ~
      vars['openvpn_instance_name'] ~ '/crlnumber' }}"
- name: "openvpn | Put crl cert to CA (S3)"
  amazon.aws.s3_object:
    aws_access_key: "{{ vars['openvpn_ca_storage_source']['aws_access_key'] |
      default(omit) }}"
    aws_secret_key: "{{ vars['openvpn_ca_storage_source']['aws_secret_key'] |
      default(omit) }}"
    bucket: "{{ vars['openvpn_ca_storage_source']['bucket'] | default(omit) }}"
    encrypt: "{{ vars['openvpn_ca_storage_source']['encrypt'] |
      default(omit) }}"
    ignore_nonexistent_bucket: "true"
    rgw: "{{ vars['openvpn_ca_storage_source']['rgw'] | default(omit) }}"
    endpoint_url: "{{ vars['openvpn_ca_storage_source']['endpoint_url'] |
      default(omit) }}"
    validate_certs: "{{ vars['openvpn_ca_storage_source']['validate_certs'] |
      default(omit) }}"
    region: "{{ vars['openvpn_ca_storage_source']['region'] | default(omit) }}"
    profile: "{{ vars['openvpn_ca_storage_source']['profile'] |
      default(omit) }}"
    mode: "put"
    object: "{{ vars['openvpn_ca_storage_source']['object_prefix'] ~ '/' ~
      vars['openvpn_ca_storage_source']['crl_path'] + '/crl.pem' }}"
    overwrite: "different"
    src: "{{ vars['openvpn_local_fetch_dir'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '/crl.pem' }}"
