---
- name: "openvpn | Import deploy user configuration tasks"
  ansible.builtin.import_tasks:
    file: "user.d/deploy.yml"
- name: "openvpn | Import make user archive tasks"
  ansible.builtin.import_tasks:
    file: "user.d/make_archive.yml"
- name: "openvpn | Import send user e-mail tasks"
  ansible.builtin.import_tasks:
    file: "user.d/send_mail.yml"
