---
- name: "openvpn | Assert that user is defined"
  ansible.builtin.assert:
    that:
      - "vars['openvpn_target_user'] is defined"
      - "vars['openvpn_target_user'] not in ['', [], None]"
    fail_msg: "User is not defined"
    success_msg: "{{ 'User is defined: ' ~ vars['openvpn_target_user'] }}"
    quiet: "true"
- name: "openvpn | Set facts about OpenVPN environment"
  ansible.builtin.set_fact:
    openvpn_ca_storage_type: "{{ hostvars[inventory_hostname]['openvpn'] |
      community.general.json_query('[].ca_storage[].storage_type | [0]') }}"
    openvpn_ca_storage_source: "{{ hostvars[inventory_hostname]['openvpn'] |
      community.general.json_query('[].ca_storage[].storage_source[] | [0]') }}"
    openvpn_email_settings: "{{ hostvars[inventory_hostname]['openvpn'] |
      community.general.json_query('[].global_settings[].email[] | [0]') }}"
    openvpn_ldap_settings: "{{ hostvars[inventory_hostname]['openvpn'] |
      community.general.json_query('[].global_settings[].ldap[] | [0]') }}"
    openvpn_instance_name: "{{ vars['openvpn_target_user'] }}"
