---
- name: "openvpn | Override OpenVPN service configuration"
  ansible.builtin.template:
    src: "openvpn_service.j2"
    dest: "{{ '/etc/systemd/system/' +
      hostvars[inventory_hostname]['openvpn_' + ovpn['type'] + '_service'] +
      ovpn['name'] + '.service.d/' + ovpn['name'] + '.conf' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ hostvars[inventory_hostname]['openvpn'] |
    community.general.json_query(\"[].openvpn_settings[?name=='\" ~
    vars['outer_item']['name'] ~ \"']\") | flatten(levels=1) }}"
  loop_control:
    loop_var: "ovpn"
    label: "{{ 'openvpn-' + ovpn['type'] + ': ' ~ ovpn['name'] }}"
  notify:
    - "Daemon reload"
  when:
    - "vars['openvpn_systemd_override'] is defined"
    - "vars['openvpn_systemd_override'] == 'true'"
- name: "openvpn | Enable OpenVPN service"
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['openvpn_' + ovpn['type'] +
      '_service'] ~ ovpn['name'] }}"
    enabled: "yes"
  loop: "{{ hostvars[inventory_hostname]['openvpn'] |
    community.general.json_query(\"[].openvpn_settings[?name=='\" ~
    vars['outer_item']['name'] ~ \"']\") | flatten(levels=1) }}"
  loop_control:
    loop_var: "ovpn"
    label: "{{ 'openvpn-' + ovpn['type'] + ': ' ~ ovpn['name'] }}"
  when:
    - "hostvars[inventory_hostname]['openvpn'] is defined"
    - "hostvars[inventory_hostname]['openvpn'] not in ['', [], None]"
    - "hostvars[inventory_hostname]['openvpn'] |
       community.general.json_query(vars['openvpn_enable']) is defined"
    - "hostvars[inventory_hostname]['openvpn'] |
       community.general.json_query(vars['openvpn_enable']) == 'true'"
  vars:
    openvpn_enable: "[] | map(&enable || 'false', @) | [0]"
