---
- name: "openvpn | Gather deployment host facts"
  ansible.builtin.setup:
- name: "openvpn | Add the OS specific varibles"
  ansible.builtin.include_vars:
    file: "{{ hostvars[inventory_hostname]['ansible_os_family'] + '.yml' }}"
